name: blurhash_ffi

repository: https://github.com/folksable/blurhash_ffi
issue_tracker: https://github.com/folksable/blurhash_ffi/issues
funding: 
  - https://github.com/sponsors/folksable

environment:
  sdk: ^3.10.0

# workspace:
#   - packages/dart_blurhash_ffi
#   - packages/flutter_blurhash_ffi