pub fn decode83(c: char) -> Option<usize> {
    match c {
        '0'..='9' => Some((c as u8 - b'0') as usize),
        'A'..='Z' => Some((c as u8 - b'A' + 10) as usize),
        'a'..='z' => Some((c as u8 - b'a' + 36) as usize),
        '#' => Some(62),
        '$' => Some(63),
        '%' => Some(64),
        '*' => Some(65),
        '+' => Some(66),
        ',' => Some(67),
        '-' => Some(68),
        '.' => Some(69),
        ':' => Some(70),
        ';' => Some(71),
        '=' => Some(72),
        '?' => Some(73),
        '@' => Some(74),
        '[' => Some(75),
        ']' => Some(76),
        '^' => Some(77),
        '_' => Some(78),
        '{' => Some(79),
        '|' => Some(80),
        '}' => Some(81),
        '~' => Some(82),
        _ => None,
    }
}
